Update README.md
JennieOhyoung/code_review pull request #3
Opened 2016-11-06 06:20 UTC by JennieOhyoung

2016-11-06 06:22 UTC, drock1 requested changes

2016-11-06 06:22 UTC, drock1 commented on README.md
> +changes changes changes
add another change

2016-11-06 06:22 UTC, drock1 commented on README.md
> -# code_review
suggestion #2

2016-11-06 06:22 UTC, JennieOhyoung commented on README.md
> -# code_review
got this

2016-11-06 06:22 UTC, JennieOhyoung commented on README.md
> +changes changes changes
ok

2016-11-06 19:01 UTC, JennieOhyoung commented on README.md
> -# code_review
comment on commit 1

2016-11-07 21:14 UTC, gnuoyhoeinnej approved these changes

2016-11-09 19:09 UTC, gnuoyhoeinnej requested changes
can you make changes with pending request as admin?

2016-11-09 19:33 UTC, gnuoyhoeinnej approved these changes

2016-11-17 18:28 UTC, gnuoyhoeinnej approved these changes

2016-11-17 18:34 UTC, gnuoyhoeinnej submitted a review, later dismissed
fix this shit

2016-11-17 18:36 UTC, gnuoyhoeinnej approved these changes

2016-11-17 18:36 UTC, gnuoyhoeinnej requested changes
found another shitty thing to fix

2016-11-17 18:56 UTC, gnuoyhoeinnej approved these changes

2016-11-17 18:57 UTC, gnuoyhoeinnej requested changes
disproves

2018-08-06 21:37 UTC, JennieOhyoung commented
test test

2018-08-06 21:39 UTC, JennieOhyoung commented
testing comment via email #2



On Mon, Aug 6, 2018 at 2:37 PM, Jennie Ohyoung <notifications@github.com>
wrote:

> test test
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/JennieOhyoung/code_review/pull/3#issuecomment-410861006>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFIvql9eYM0JHYlcwJ_t2GFSaZsyB40lks5uOLcngaJpZM4Kqeu1>
> .
>

2018-08-15 19:09 UTC, closed without merging